language: dart
dart:
  - stable/raw/2.0.0

sudo: required
env:
- TEST_VALUE=1 TEST_BOOL=true TEST_DB_ENV_VAR=postgres://user:password@host:5432/dbname
script:
- pub run test -j 1 -r expanded
branches:
  only:
    - master
