name: safe_config
description: A safe and convenient way to read YAML configuration files.
version: 2.0.0-beta
author: stable|kernel <jobs@stablekernel.com>
homepage: http://stablekernel.com
documentation:

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  yaml: '>=2.1.8 <3.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
